# Dockerfile.streamlit
FROM python:3.11

WORKDIR /frontend
COPY . /frontend

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8501
CMD ["streamlit", "run", "frontend/front.py", "--server.port=8501", "--server.address=0.0.0.0"]